### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by savantning** [wouterkool/attention-learn-to-route#3]
Hi, I enjoy your paper, and i met issues about your code, i don't know how to solve it, my environment:
cuda: 8.0 V8.0.61
python: 3.5
Pytorch: 0.4

 this is my print

{'baseline': None,
 'batch_size': 512,
 'bl_alpha': 0.05,
 'bl_warmup_epochs': 0,
 'checkpoint_epochs': 1,
 'embedding_dim': 128,
 'epoch_size': 1280000,
 'epoch_start': 0,
 'eval_batch_size': 1024,
 'eval_only': False,
 'exp_beta': 0.8,
 'graph_size': 20,
 'hidden_dim': 128,
 'load_path': None,
 'log_dir': 'logs',
 'log_step': 50,
 'lr_critic': 0.0001,
 'lr_decay': 1.0,
 'lr_model': 0.0001,
 'max_grad_norm': 1.0,
 'model': 'attention',
 'n_encode_layers': 3,
 'n_epochs': 100,
 'no_cuda': False,
 'no_progress_bar': False,
 'no_tensorboard': False,
 'normalization': 'batch',
 'output_dir': 'outputs',
 'problem': 'tsp',
 'resume': None,
 'run_name': 'run_20180906T163914',
 'save_dir': 'outputs/tsp_20/run_20180906T163914',
 'seed': 1234,
 'tanh_clipping': 10.0,
 'use_cuda': True,
 'val_dataset': None,
 'val_size': 10000}
Traceback (most recent call last):
  File "/home/savantning/PycharmProjects/attention-tsp-master/run.py", line 168, in <module>
    run(get_options())
  File "/home/savantning/PycharmProjects/attention-tsp-master/run.py", line 67, in run
    opts.use_cuda
  File "/home/savantning/PycharmProjects/attention-tsp-master/utils.py", line 26, in maybe_cuda_model
    model.cuda()
  File "/home/savantning/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/savantning/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/savantning/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/savantning/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: unknown error

Process finished with exit code 1

thank you very much

**Comment by wouterkool** [comment]
Hi!

Note that the code was developed for PyTorch 0.3 so you may need to make some changes. I am not sure if this error relates to the code or your environment? Can you please confirm that you have no problems moving a simple model (eg nn.Linear) to the GPU?

`>> python -c"import torch; model = torch.nn.Linear(2, 3); model.cuda(); print(model.weight);"
Parameter containing:
tensor([[ 0.5493,  0.4590],
        [-0.2906, -0.5688],
        [ 0.0692,  0.3211]], device='cuda:0')`

Wouter

**Comment by wouterkool** [comment]
Given your thumbs up, I'll assume this fixed the problem so I'll close the issue.
